org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
kotlin.code.style=official

group=community.flock.wirespec.kotest
version=0.0.0-SNAPSHOT

kotlinVersion=2.3.0
springBootVersion=3.4.1
springDependencyManagementVersion=1.1.7
wirespecVersion=0.20.0-RC.2
wirespecExtractorVersion=0.0.13
kotestVersion=6.1.11
kotestSpringExtensionVersion=6.1.11
