package io.kotest.extensions.spring.wirespec.dsl

import community.flock.wirespec.integration.kotest.kotestWirespecKotlinGenerator
import community.flock.wirespec.kotlin.Wirespec
import io.kotest.property.Arb
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.arbitrary
import java.util.concurrent.ConcurrentHashMap
import kotlin.random.Random

/**
 * Receiver exposed as `arb` inside a `scenario { ... }` block.
 *
 * Re-exposes the existing `wirespec-jvm:kotest-jvm` adapter — every generated
 * `*Generator` (e.g. `CreatePetRequestGenerator`) walks the Wirespec IR and
 * dispatches into a [Wirespec.Generator] backed by kotest [Arb]s. This receiver
 * does *not* reinvent generation; it just makes lookup ergonomic for tests.
 *
 * Two access paths:
 *
 *   - **Direct value**: `arb.gen<CreatePetRequest>()` — finds
 *     `…generator.CreatePetRequestGenerator.INSTANCE.generate(genBackend, [])`
 *     by deriving the generator package from the requested type's package.
 *
 *   - **Arb wrapper**: `arb.of<CreatePetRequest>()` — returns an `Arb<T>` for use
 *     with slot setters that accept Arbs (`body(arb.of<CreatePetRequest>())`).
 *
 * The per-iteration [RandomSource] threads into the underlying kotest generator's
 * seed so failures are reproducible (kotest-property's `checkAll` prints the seed
 * on failure).
 */
@WirespecScenarioDsl
class ArbReceiver internal constructor(
    internal val randomSource: RandomSource,
) {

    /** The kotest-backed [Wirespec.Generator] used by every `*Generator.generate(...)` invocation. */
    @PublishedApi
    internal val generator: Wirespec.Generator =
        kotestWirespecKotlinGenerator(seed = randomSource.random.nextLong())

    /**
     * Build a fresh value of [T] using the Wirespec-generated companion
     * `…generator.<T>Generator`. Throws a clear error if [T] isn't a
     * Wirespec-generated model type with a paired generator.
     */
    inline fun <reified T : Any> gen(): T {
        @Suppress("UNCHECKED_CAST")
        return generatorFor(T::class.java).generate(generator, emptyList()) as T
    }

    /**
     * Wrap [gen] in an [Arb] for slot setters that expect one.
     *
     * Each draw threads a fresh sample through the per-iteration generator,
     * keeping property-based shrinking aligned with the kotest random source.
     */
    inline fun <reified T : Any> of(): Arb<T> = arbitrary { gen<T>() }

    @PublishedApi
    internal fun generatorFor(modelClass: Class<*>): GeneratorHandle = cache.computeIfAbsent(modelClass) {
        // Generated package convention from the Wirespec IR emitter:
        //   <root>.model.<X>          → the user-facing type
        //   <root>.generator.<X>Generator  → the IR-emitted Arb adapter
        val modelPkg = modelClass.`package`?.name
            ?: error("${modelClass.simpleName}: no package; was this class actually generated by Wirespec?")
        val generatorPkg = modelPkg.removeSuffix(".model") + ".generator"
        val generatorName = "$generatorPkg.${modelClass.simpleName}Generator"
        val cls = runCatching { Class.forName(generatorName, true, modelClass.classLoader) }
            .getOrElse {
                error(
                    "Could not locate $generatorName for ${modelClass.simpleName}. " +
                        "The Wirespec IR Kotlin emitter must be enabled (emitterClass = KotlinIrEmitter::class.java) " +
                        "so per-type generators are emitted alongside models.",
                )
            }
        val instance = cls.getDeclaredField("INSTANCE").get(null)
        val method = cls.declaredMethods.firstOrNull { it.name == "generate" && it.parameterCount == 2 }
            ?: error("$generatorName has no `generate(generator, path)` method — unexpected shape.")
        GeneratorHandle(instance = instance, generateMethod = method)
    }

    @PublishedApi
    internal class GeneratorHandle(
        private val instance: Any,
        private val generateMethod: java.lang.reflect.Method,
    ) {
        fun generate(generator: Wirespec.Generator, path: List<String>): Any =
            generateMethod.invoke(instance, generator, path)
    }

    companion object {
        private val cache = ConcurrentHashMap<Class<*>, GeneratorHandle>()
    }
}
