package io.kotest.extensions.spring.wirespec.example

import io.kotest.extensions.spring.wirespec.SpringScenarioSpec
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.PetCreate
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.PetDelete
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.PetGet
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.PetList
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.PetUpdate
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.petCreate
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.petDelete
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.petGet
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.petList
import io.kotest.extensions.spring.wirespec.example.generated.endpoint.petUpdate
import io.kotest.extensions.spring.wirespec.example.generated.model.CreatePetRequest
import io.kotest.extensions.spring.wirespec.example.generated.model.UpdatePetRequest
import io.kotest.matchers.shouldBe

/**
 * Mirror of PetScenariosSpec using only the typesafe per-endpoint DSL
 * (petCreate, petGet, petUpdate, petDelete, petList) generated by
 * TypesafeDslEmitter. No endpoint(X.Handler) call sites.
 */
class PetScenariosTypesafeDslSpec : SpringScenarioSpec(ExampleApplication::class, {

    scenario("pet CRUD via typesafe DSL", iterations = 3) {
        val petId = petCreate {
            body(CreatePetRequest(name = "Fido", species = "dog"))
        }.returning<PetCreate.Response201, String> { it.body.id }

        petGet { path(petId) }.expecting<PetGet.Response200>()

        petUpdate {
            path(petId)
            body(UpdatePetRequest(name = "Rex", species = null))
        }.expecting<PetUpdate.Response200> { it.body.name shouldBe "Rex" }

        petDelete { path(petId) }.expecting<PetDelete.Response204>()
        petGet { path(petId) }.expecting<PetGet.Response404>()
    }

    scenario("typesafe queries", iterations = 1) {
        petCreate { body(CreatePetRequest("Whiskers", "cat")) }
        petCreate { body(CreatePetRequest("Bubbles", "fish")) }

        petList { query(limit = 10, offset = 0) }
            .expecting<PetList.Response200> { resp ->
                resp.body.content.size shouldBe resp.body.total.coerceAtMost(10)
            }
    }

    // The following are checked manually — uncomment to verify each fails to
    // compile, then re-comment. The typesafe DSL prevents both at compile time:
    //
    //   // COMPILE-ERROR-EXPECTED: "Unresolved reference 'path'"
    //   //   petCreate has no path slot — PetCreate.Path is empty
    //   scenario("wrong slot") { petCreate { path("p-1") } }
    //
    //   // COMPILE-ERROR-EXPECTED: "Type argument is not within its bounds"
    //   //   PetGet.Response200 is not a PetCreate.Response<*>
    //   scenario("wrong response variant") { petCreate { expecting<PetGet.Response200>() } }
    //
    // Last manually verified: 2026-05-21.
})
