plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    id("com.gradle.plugin-publish") version "1.3.0"
    id("com.vanniktech.maven.publish.base") version "0.30.0"
}

group = "community.flock.wirespec.kotest"
version = (providers.gradleProperty("version").orNull) ?: "0.0.0-SNAPSHOT"

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
    mavenLocal()
}

dependencies {
    implementation(gradleApi())
    implementation("community.flock.wirespec.plugin.gradle:community.flock.wirespec.plugin.gradle.gradle.plugin:0.20.0-RC.2")
    implementation("community.flock.wirespec.spring:wirespec-spring-extractor-gradle-plugin:0.0.13")
    // The Kotest scenario DSL is now generated by wirespec's own `KotestDslExtension`
    // (shipped on `kotest-jvm`) driven by the `KotlinIrEmitter` (from the Kotlin
    // emitter artifact) — replacing this repo's former `kotest-wirespec-emitter`.
    implementation("community.flock.wirespec.integration:kotest-jvm:0.20.0-RC.2")
    implementation("community.flock.wirespec.compiler.emitters:kotlin-jvm:0.20.0-RC.2")

    testImplementation(kotlin("test"))
    testImplementation(gradleTestKit())
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

gradlePlugin {
    website.set("https://github.com/kotest/kotest-wirespec")
    vcsUrl.set("https://github.com/kotest/kotest-wirespec.git")
    plugins {
        create("kotestWirespec") {
            id = "community.flock.wirespec.kotest"
            displayName = "Kotest Wirespec"
            description = "Extracts Wirespec contracts from Spring controllers and exposes a property-based scenario DSL for Kotest."
            tags.set(listOf("kotest", "spring", "wirespec", "property-based", "contract-testing"))
            implementationClass = "io.kotest.extensions.wirespec.gradle.KotestWirespecPlugin"
        }
    }
}

tasks.test {
    useJUnitPlatform()
}

mavenPublishing {
    configureBasedOnAppliedPlugins()
    publishToMavenCentral(
        com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL,
        automaticRelease = true,
    )
    signAllPublications()
    coordinates(group.toString(), "kotest-wirespec-gradle-plugin", version.toString())
    pom {
        name.set("kotest-wirespec-gradle-plugin")
        description.set("Extracts Wirespec contracts from Spring controllers and exposes a property-based scenario DSL for Kotest.")
        url.set("https://github.com/flock-community/kotest-wirespec")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("wilmveel")
                name.set("Willem Veelenturf")
                email.set("willem.veelenturf@flock.community")
                organization.set("Flock. Community")
                organizationUrl.set("https://flock.community")
            }
        }
        scm {
            connection.set("scm:git:git://github.com/flock-community/kotest-wirespec.git")
            developerConnection.set("scm:git:ssh://github.com:flock-community/kotest-wirespec.git")
            url.set("https://github.com/flock-community/kotest-wirespec")
        }
    }
}
